[package]
name = "rocky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librocksdb-sys = "0.11.0+8.1.1"
